// ===== Game Notification Types =====

export enum NotificationGameForPlayerEnum {
  NT_GAME_FOR_PLAYER_INVITE = 'NT_GAME_FOR_PLAYER_INVITE',
  NT_GAME_FOR_PLAYER_GAME_READY = 'NT_GAME_FOR_PLAYER_GAME_READY',
  NT_GAME_FOR_PLAYER_GAME_IN_PROGRESS = 'NT_GAME_FOR_PLAYER_GAME_IN_PROGRESS',
  NT_GAME_FOR_PLAYER_GAME_PAUSED = 'NT_GAME_FOR_PLAYER_GAME_PAUSED',
  NT_GAME_FOR_PLAYER_GAME_FINISHED = 'NT_GAME_FOR_PLAYER_GAME_FINISHED',
  NT_GAME_FOR_PLAYER_KICKED = 'NT_GAME_FOR_PLAYER_KICKED',
}

export enum NotificationGameForOwnerEnum {
  NT_GAME_FOR_OWNER_PLAYER_REJECTED = 'NT_GAME_FOR_OWNER_PLAYER_REJECTED',
  NT_GAME_FOR_OWNER_PLAYER_LEFT = 'NT_GAME_FOR_OWNER_PLAYER_LEFT',
  NT_GAME_FOR_OWNER_PLAYER_ACCEPTED = 'NT_GAME_FOR_OWNER_PLAYER_ACCEPTED',
  NT_GAME_FOR_OWNER_PLAYER_SELECTED_CHARACTER = 'NT_GAME_FOR_OWNER_PLAYER_SELECTED_CHARACTER',
}
